### ISSUE TITLE
Feature Request: Additional logging information

### ISSUE THREAD

**Issue by danhamill** [HydrologicEngineeringCenter/Vortex#6]
It would be nice if you could add some additional logging information in the terminal when you launch `importer.bat` 

1. ) Number of selected files on the initial file selection menu
2.) Path to selected shapefile

I have found that either I am not selecting all the files in the initial step (maybe window explorer is slow to load) or vortex is not processing all the rasters.  Either way, it would be nice to have some additional information about the import process.

**Comment by danhamill** [comment]
After watching the terminal for a while I saw:

```cmd
    -----DSS---ZOPEN:  Existing File Opened,  File: C:\workspace\ririe\HMS\data\precip\Truckee_Precip_2016.dss
                       Unit:    3;  DSS Versions - Software: 6-YN, File: 6-WE,  Library 7-HI


 -----DSS---ZWRITE Unit    3; Vers.    1:  /RIRIE/PRECIPITATION/PRECIPITATION/09FEB2016:0500/09FEB2016:0600/MRMS/
Aug 10, 2020 5:43:19 PM ucar.nc2.grib.collection.GribIosp readData
SEVERE: Failed to readData
java.io.FileNotFoundException: data file not found = C:\workspace\ririe\HMS\data\precip\GaugeCorr_QPE_01H_00.00_20160513-070000.grib2
        at ucar.nc2.grib.collection.GribCollectionImmutable.getDataRaf(GribCollectionImmutable.java:944)
        at ucar.nc2.grib.collection.GribIosp$DataReader.read(GribIosp.java:1086)
        at ucar.nc2.grib.collection.GribIosp.readDataFromCollection(GribIosp.java:1018)
        at ucar.nc2.grib.collection.GribIosp.readData(GribIosp.java:963)
        at ucar.nc2.NetcdfFile.readData(NetcdfFile.java:2026)
        at ucar.nc2.Variable.reallyRead(Variable.java:874)
        at ucar.nc2.Variable._read(Variable.java:845)
        at ucar.nc2.Variable.read(Variable.java:723)
        at ucar.nc2.dataset.VariableDS.reallyRead(VariableDS.java:523)
        at ucar.nc2.dataset.VariableDS._read(VariableDS.java:507)
        at ucar.nc2.dataset.VariableDS._read(VariableDS.java:531)
        at ucar.nc2.Variable.read(Variable.java:709)
        at ucar.nc2.Variable.read(Variable.java:655)
        at ucar.nc2.dt.grid.GeoGrid.readDataSlice(GeoGrid.java:606)
        at ucar.nc2.dt.grid.GeoGrid.readDataSlice(GeoGrid.java:517)
        at mil.army.usace.hec.vortex.io.NetcdfDataReader.getData(NetcdfDataReader.java:540)
        at mil.army.usace.hec.vortex.io.NetcdfDataReader.getDto(NetcdfDataReader.java:97)
        at mil.army.usace.hec.vortex.io.ImportableUnit.lambda$process$0(ImportableUnit.java:93)
        at java.util.stream.ForEachOps$ForEachOp$OfInt.accept(ForEachOps.java:204)
        at java.util.stream.Streams$RangeIntSpliterator.forEachRemaining(Streams.java:110)
        at java.util.Spliterator$OfInt.forEachRemaining(Spliterator.java:693)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
        at java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:290)
        at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinTask.doInvoke(ForkJoinTask.java:401)
        at java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:734)
        at java.util.stream.ForEachOps$ForEachOp.evaluateParallel(ForEachOps.java:159)
        at java.util.stream.ForEachOps$ForEachOp$OfInt.evaluateParallel(ForEachOps.java:188)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233)
        at java.util.stream.IntPipeline.forEach(IntPipeline.java:427)
        at java.util.stream.IntPipeline$Head.forEach(IntPipeline.java:584)
        at mil.army.usace.hec.vortex.io.ImportableUnit.process(ImportableUnit.java:91)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
        at java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:290)
        at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

Aug 10, 2020 5:43:19 PM ucar.nc2.dt.grid.GeoGrid readDataSlice
SEVERE: GeoGrid.getdataSlice() on variable GaugeCorrQPE01H_altitude_above_msl dataset C:/workspace/ririe/HMS/data/precip/2016/GaugeCorr_QPE_01H_00.00_20160513-070000.grib2
java.io.FileNotFoundException: data file not found = C:\workspace\ririe\HMS\data\precip\GaugeCorr_QPE_01H_00.00_20160513-070000.grib2
        at ucar.nc2.grib.collection.GribCollectionImmutable.getDataRaf(GribCollectionImmutable.java:944)
        at ucar.nc2.grib.collection.GribIosp$DataReader.read(GribIosp.java:1086)
        at ucar.nc2.grib.collection.GribIosp.readDataFromCollection(GribIosp.java:1018)
        at ucar.nc2.grib.collection.GribIosp.readData(GribIosp.java:963)
        at ucar.nc2.NetcdfFile.readData(NetcdfFile.java:2026)
        at ucar.nc2.Variable.reallyRead(Variable.java:874)
        at ucar.nc2.Variable._read(Variable.java:845)
        at ucar.nc2.Variable.read(Variable.java:723)
        at ucar.nc2.dataset.VariableDS.reallyRead(VariableDS.java:523)
        at ucar.nc2.dataset.VariableDS._read(VariableDS.java:507)
        at ucar.nc2.dataset.VariableDS._read(VariableDS.java:531)
        at ucar.nc2.Variable.read(Variable.java:709)
        at ucar.nc2.Variable.read(Variable.java:655)
        at ucar.nc2.dt.grid.GeoGrid.readDataSlice(GeoGrid.java:606)
        at ucar.nc2.dt.grid.GeoGrid.readDataSlice(GeoGrid.java:517)
        at mil.army.usace.hec.vortex.io.NetcdfDataReader.getData(NetcdfDataReader.java:540)
        at mil.army.usace.hec.vortex.io.NetcdfDataReader.getDto(NetcdfDataReader.java:97)
        at mil.army.usace.hec.vortex.io.ImportableUnit.lambda$process$0(ImportableUnit.java:93)
        at java.util.stream.ForEachOps$ForEachOp$OfInt.accept(ForEachOps.java:204)
        at java.util.stream.Streams$RangeIntSpliterator.forEachRemaining(Streams.java:110)
        at java.util.Spliterator$OfInt.forEachRemaining(Spliterator.java:693)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
        at java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:290)
        at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinTask.doInvoke(ForkJoinTask.java:401)
        at java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:734)
        at java.util.stream.ForEachOps$ForEachOp.evaluateParallel(ForEachOps.java:159)
        at java.util.stream.ForEachOps$ForEachOp$OfInt.evaluateParallel(ForEachOps.java:188)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233)
        at java.util.stream.IntPipeline.forEach(IntPipeline.java:427)
        at java.util.stream.IntPipeline$Head.forEach(IntPipeline.java:584)
        at mil.army.usace.hec.vortex.io.ImportableUnit.process(ImportableUnit.java:91)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
        at java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:290)
        at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

Aug 10, 2020 5:43:19 PM mil.army.usace.hec.vortex.io.NetcdfDataReader getData
SEVERE: java.io.FileNotFoundException: data file not found = C:\workspace\ririe\HMS\data\precip\GaugeCorr_QPE_01H_00.00_20160513-070000.grib2
java.io.IOException: java.io.FileNotFoundException: data file not found = C:\workspace\ririe\HMS\data\precip\GaugeCorr_QPE_01H_00.00_20160513-070000.grib2
        at ucar.nc2.dt.grid.GeoGrid.readDataSlice(GeoGrid.java:609)
        at ucar.nc2.dt.grid.GeoGrid.readDataSlice(GeoGrid.java:517)
        at mil.army.usace.hec.vortex.io.NetcdfDataReader.getData(NetcdfDataReader.java:540)
        at mil.army.usace.hec.vortex.io.NetcdfDataReader.getDto(NetcdfDataReader.java:97)
        at mil.army.usace.hec.vortex.io.ImportableUnit.lambda$process$0(ImportableUnit.java:93)
        at java.util.stream.ForEachOps$ForEachOp$OfInt.accept(ForEachOps.java:204)
        at java.util.stream.Streams$RangeIntSpliterator.forEachRemaining(Streams.java:110)
        at java.util.Spliterator$OfInt.forEachRemaining(Spliterator.java:693)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
        at java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:290)
        at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinTask.doInvoke(ForkJoinTask.java:401)
        at java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:734)
        at java.util.stream.ForEachOps$ForEachOp.evaluateParallel(ForEachOps.java:159)
        at java.util.stream.ForEachOps$ForEachOp$OfInt.evaluateParallel(ForEachOps.java:188)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233)
        at java.util.stream.IntPipeline.forEach(IntPipeline.java:427)
        at java.util.stream.IntPipeline$Head.forEach(IntPipeline.java:584)
        at mil.army.usace.hec.vortex.io.ImportableUnit.process(ImportableUnit.java:91)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
        at java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:290)
        at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: java.io.FileNotFoundException: data file not found = C:\workspace\ririe\HMS\data\precip\GaugeCorr_QPE_01H_00.00_20160513-070000.grib2
        at ucar.nc2.grib.collection.GribCollectionImmutable.getDataRaf(GribCollectionImmutable.java:944)
        at ucar.nc2.grib.collection.GribIosp$DataReader.read(GribIosp.java:1086)
        at ucar.nc2.grib.collection.GribIosp.readDataFromCollection(GribIosp.java:1018)
        at ucar.nc2.grib.collection.GribIosp.readData(GribIosp.java:963)
        at ucar.nc2.NetcdfFile.readData(NetcdfFile.java:2026)
        at ucar.nc2.Variable.reallyRead(Variable.java:874)
        at ucar.nc2.Variable._read(Variable.java:845)
        at ucar.nc2.Variable.read(Variable.java:723)
        at ucar.nc2.dataset.VariableDS.reallyRead(VariableDS.java:523)
        at ucar.nc2.dataset.VariableDS._read(VariableDS.java:507)
        at ucar.nc2.dataset.VariableDS._read(VariableDS.java:531)
        at ucar.nc2.Variable.read(Variable.java:709)
        at ucar.nc2.Variable.read(Variable.java:655)
        at ucar.nc2.dt.grid.GeoGrid.readDataSlice(GeoGrid.java:606)
        ... 28 more

 -----DSS---ZWRITE Unit    3; Vers.    1:  /RIRIE/PRECIPITATION/PRECIPITATION/05JAN2016:2200/05JAN2016:2300/MRMS/
REM Lots of additional ZWRITE
 -----DSS---ZWRITE Unit    3; Vers.    1:  /RIRIE/PRECIPITATION/PRECIPITATION/28MAY2016:0500/28MAY2016:0600/MRMS/
java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at importer.controller.WizardController$1.call(WizardController.java:169)
        at importer.controller.WizardController$1.call(WizardController.java:163)
        at javafx.concurrent.Task$TaskCallable.call(Task.java:1423)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalArgumentException: java.lang.IllegalArgumentException: Resampler requires input grid
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:593)
        at java.util.concurrent.ForkJoinTask.reportException(ForkJoinTask.java:677)
        at java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:735)
        at java.util.stream.ForEachOps$ForEachOp.evaluateParallel(ForEachOps.java:159)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(ForEachOps.java:173)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233)
        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:485)
        at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:650)
        at mil.army.usace.hec.vortex.io.BatchImporter.process(BatchImporter.java:85)
        at importer.controller.Step3Controller.submit(Step3Controller.java:173)
        ... 9 more
Caused by: java.lang.IllegalArgumentException: Resampler requires input grid
        at mil.army.usace.hec.vortex.geo.Resampler$ResamplerBuilder.build(Resampler.java:73)
        at mil.army.usace.hec.vortex.io.ImportableUnit.lambda$process$0(ImportableUnit.java:117)
        at java.util.stream.ForEachOps$ForEachOp$OfInt.accept(ForEachOps.java:204)
        at java.util.stream.Streams$RangeIntSpliterator.forEachRemaining(Streams.java:110)
        at java.util.Spliterator$OfInt.forEachRemaining(Spliterator.java:693)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
        at java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:290)
 -----DSS---ZWRITE Unit    3; Vers.    1:  /RIRIE/PRECIPITATION/PRECIPITATION/15NOV2015:1400/15NOV2015:1500/MRMS/
        at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinTask.doInvoke(ForkJoinTask.java:401)
        at java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:734)
        at java.util.stream.ForEachOps$ForEachOp.evaluateParallel(ForEachOps.java:159)
        at java.util.stream.ForEachOps$ForEachOp$OfInt.evaluateParallel(ForEachOps.java:188)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233)
        at java.util.stream.IntPipeline.forEach(IntPipeline.java:427)
        at java.util.stream.IntPipeline$Head.forEach(IntPipeline.java:584)
        at mil.army.usace.hec.vortex.io.ImportableUnit.process(ImportableUnit.java:91)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
        at java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:290)
        at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
 -----DSS---ZWRITE Unit    3; Vers.    1:  /RIRIE/PRECIPITATION/PRECIPITATION/08JUN2016:2000/08JUN2016:2100/MRMS/
 -----DSS---ZWRITE Unit    3; Vers.    1:  /RIRIE/PRECIPITATION/PRECIPITATION/20NOV2015:2000/20NOV2015:2100/MRMS/
 -----DSS---ZWRITE Unit    3; Vers.    1:  /RIRIE/PRECIPITATION/PRECIPITATION/14JUN2016:1500/14JUN2016:1600/MRMS/
 -----DSS---ZWRITE Unit    3; Vers.    1:  /RIRIE/PRECIPITATION/PRECIPITATION/25MAR2016:2200/25MAR2016:2300/MRMS/
```
What seems interesting is that the missing file indicated in the file path indicated by `java.io.FileNotFoundException: ` is not the same as `SEVERE: GeoGrid.getdataSlice() ` file path.

**Comment by danhamill** [comment]
Any thoughts on why this is happening?  Using the newest release, I am not getting an "Import Complete" message when no DSS records are in the output file.

**Comment by tombrauer** [comment]
Can you upload your data file? I'll try to reproduce. It looks like you can upload in the chat. If it's too big I can send instructions for uploading to our dropbox.
