### ISSUE TITLE
geo not recognized

### ISSUE THREAD

**Issue by ranleu** [HydrologicEngineeringCenter/Vortex#92]
I am trying to automate importing of *.nc files. I've taken the script and batch samples here and modified them to work with Jython-Standalone and to work with the vortex installation included in HEC-HMS as follows:

```
SET "VORTEX_HOME=C:\Program Files\HEC\HEC-HMS\4.10"
SET "PATH=%VORTEX_HOME%\bin;%VORTEX_HOME%\bin\gdal;%PATH%"
SET "PROJ_LIB=%VORTEX_HOME%\bin\gdal\projlib"
SET "GDAL_DATA=%VORTEX_HOME%\bin\gdal\gdal-data"
SET "CLASSPATH=%VORTEX_HOME%\lib\*"

"%VORTEX_HOME%\jre\bin\java.exe" -jar C:\Users\...\jython-standalone-2.7.3.jar C:\Users\...\GRID_Importer\met_data_import.py
```
and the script
```
import sys
sys.path.insert(0, 'C:/Program Files/HEC/HEC-HMS/4.10/lib/vortex-0.10.30.jar')
print sys.path

from mil.army.usace.hec.vortex.io import BatchImporter
from mil.army.usace.hec.vortex.geo import WktFactory
....
....
....
```
The first import on BatchImporter works just fine.
The problem is that ...geo.. is not being recognized and I get a vanilla error  message as follows:

```
 File "C:\Users\...\GRID_Importer\met_data_import.py", line 16, in <module>
    from mil.army.usace.hec.vortex.geo import WktFactory
ImportError: No module named geo
```
I have also tried importing other classes e.g. BatchSanitzer and it also works.
Any ideas on what might be the problem?

**Comment by tombrauer** [comment]
No worries, you are doing well to get this far on your own.

It would be:
```
geo_options = {
    'pathToShp': clip_shp,
    'targetCellSize': '2000',
    'targetEpsg': '5070',
    'resamplingMethod': 'Bilinear'
}
```
`5070` is the EPSG code for SHG.

**Comment by tombrauer** [comment]
The vortex standalone distribution does not require admin to install. I created a `C:/Programs` directory on my machine. From there I downloaded the vortex distribution and unzipped in that directory. I use 7-zip to unzip rather than the windows unzip option. I'm not sure if this is possible within your IT setup.

**Comment by ranleu** [comment]
Nope, still not working. I've installed the Vortex standalone (v. 0.11.3) and tested my batch & script on it and I get the same error no matter what Java installation I use. 

I have also tried the workaround with  'targetEpsg': '5070' and it goes a bit further but then I get the following error:

```
Traceback (most recent call last):
  File "C:\Users\....\GRID_Importer\met_data_import_v2.py", line 53, in <module>
    myImport.process()
        at mil.army.usace.hec.vortex.io.DataReader.getVariables(DataReader.java:92)
        at mil.army.usace.hec.vortex.io.BatchImporter.lambda$getDataReaders$0(BatchImporter.java:113)
        at java.base/java.lang.Iterable.forEach(Unknown Source)
        at mil.army.usace.hec.vortex.io.BatchImporter.lambda$getDataReaders$1(BatchImporter.java:112)
        at java.base/java.lang.Iterable.forEach(Unknown Source)
        at mil.army.usace.hec.vortex.io.BatchImporter.getDataReaders(BatchImporter.java:110)
        at mil.army.usace.hec.vortex.io.ConcurrentBatchImporter.process(ConcurrentBatchImporter.java:20)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
java.lang.NoClassDefFoundError: java.lang.NoClassDefFoundError: ucar/unidata/geoloc/Projection
```
for reference, line 53 of my script is:

`myImport.process()`

This feels to me as some misspelling issue. Could that be?

I will try on another computer where I have full admin rights to see if there might be some issue with local system. However if you have any other tip, I would be gratefull because at the end I need for this to run under my current system.

**Comment by tombrauer** [comment]
This is the env config that I used successfully:
```
set "VORTEX_HOME=C:\Programs\vortex-0.11.2"
set "PATH=%VORTEX_HOME%\bin;%VORTEX_HOME%\bin\gdal;%PATH%"
set "GDAL_DATA=%VORTEX_HOME%\bin\gdal\gdal-data"
set "PROJ_LIB=%VORTEX_HOME%\bin\gdal\projlib"
set "CLASSPATH=C:\Programs\jython-standalone-2.7.2.jar;%VORTEX_HOME%\lib\*"
%VORTEX_HOME%\jre\bin\java.exe -Xmx2g -Djava.library.path=%VORTEX_HOME%\bin;%VORTEX_HOME%\bin\gdal org.python.util.jython met_data_import.py
```
